# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
