# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverapi', '0002_auto_20160407_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcepath', models.CharField(max_length=200)),
                ('dest_path', models.CharField(max_length=100)),
                ('release_dir', models.CharField(max_length=100)),
                ('webapp_name', models.CharField(max_length=100)),
                ('war_name', models.CharField(max_length=100)),
                ('request_domain', models.CharField(max_length=100)),
                ('request_uri', models.CharField(max_length=100)),
                ('current_link', models.CharField(max_length=50)),
                ('host_string', models.CharField(max_length=100)),
                ('host_passwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JenkinsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
    ]
