# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverapi', '0003_deployconfig_jenkinsconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployconfig',
            name='host_passwd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deployconfig',
            name='host_string',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jenkinsconfig',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jenkinsconfig',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
